## Dependencies 
install.packages(tidyverse)
install.packages(olpsR)
install.packages(plyr)
install.packages(xtable)
install.packages(class)
install.packages(randomForest)
install.packages(fields)
install.packages(geigen)
install.packages(FNN)